INSERT INTO USER (USER_ID, NICKNAME, PASSWORD, EMAIL, IS_TUTORIAL_FINISHED) VALUES (1, 'nickname', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'yesfordev@gmail.com', 0);
INSERT INTO USER (USER_ID, NICKNAME, PASSWORD, EMAIL, IS_TUTORIAL_FINISHED) VALUES (2, 'nickname2', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'yesfor@gmail.com', 0);

INSERT INTO ROLE (ROLE_ID, ROLE_NAME) values (1, 'ROLE_USER');
INSERT INTO ROLE (ROLE_ID, ROLE_NAME) values (2, 'ROLE_ADMIN');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) values (1, '1');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) values (1, '2');
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) values (2, '1');